task: 'zju_mocap'
subject: 'p387'
experiment: 'single_gpu_hash_2_64_2048_2^19'  ######################

##############################################
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_train'
  shuffle: True             # [True] ######################
  maxiter: 100000           # [400000]
  log_interval: 10          # [20] show log information
  save_model_interval: 2000 # [50000] checkpoint
  seed: 0                   # by dj
  lossweights:
    lpips: 1.0
    mse: 0.2
    opacity: 0.0            # [0.] ######################
    l1: 0.0                 # [0.]
    psnr: 0.0               # [0.]

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'
  dump_interval: 5000       # [5000]

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_387_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_387_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5


##############################################
## EXPERIMENTS CONFIGURATIONS
resize_img_scale: 0.5

train_keyfilter: ['rays', 'motion_bases', 'motion_weights_priors', 'cnl_bbox', 'dst_posevec_69', 'motionCLIP'] # add 'motionCLIP'
test_keyfilter: ['rays', 'target_rgbs', 'motion_bases', 'motion_weights_priors','cnl_bbox', 'dst_posevec_69', 'motionCLIP'] # add 'motionCLIP'

motionCLIP:
  encoded_feats: 'motionCLIP_token[s]_nbrs[1].pkl' # token: z/s(self); neighborhoods: #neighbors 
  training_frames_poseDistinct: False ######################
  training_frames_lossDistinct: False ######################
  
total_bones: 24
bbox_offset: 0.3  

resume: False
load_net: latest

patch:
  sample_subject_ratio: 0.8 # [0.8] ######################
  N_patches: 6              # try: 10; [6] ######################
  size: 20                  # try: 16; single_gpu [20]; adventure[32] ######################

network:
  ignore_pose_correction: False
  ignore_non_rigid_motions: False 
  apply_hash_coding: True

netchunk_per_gpu: 308000 # dj: [307200=2400*128] number of pts sent through network in parallel, decrease if running out of memory