category: 'superhumannerf'
task: 'zju_mocap'
subject: 'p387'
experiment: 'single_gpu_hash_2_64_2048_2^19_dir_48_16_lrate_decay_100_0.0005_l1loss_0.2_opacloss_1_100000_N_patches_6_size_20_non_rigid_5_128_test1'
logdir: '../experiments/superhumannerf/zju_mocap/p387/single_gpu_hash_2_64_2048_2^19_dir_48_16_lrate_decay_100_0.0005_l1loss_0.2_opacloss_1_100000_N_patches_6_size_20_non_rigid_5_128_test1'
primary_gpus: [0]
secondary_gpus: [0]
##############################################3
## Network Specs

# modules
network_module: 'core.nets.human_nerf.network'
trainer_module: 'core.train.trainers.human_nerf.trainer'
lr_updater_module: 'core.train.trainers.human_nerf.lr_updaters.exp_decay'
optimizer_module: 'core.train.optimizers.human_nerf.optimizer'

mweight_volume:
  module: 'core.nets.human_nerf.mweight_vol_decoders.deconv_vol_decoder'
  embedding_size: 256
  volume_size: 32
  dst_voxel_size: 0.0625

non_rigid_motion_mlp:
  mlp_width: 128
  mlp_depth: 5
  kick_in_iter: 10000
  full_band_iter: 50000

pose_decoder:
  module: 'core.nets.human_nerf.pose_decoders.mlp_delta_body_pose'
  embedding_size: 69
  mlp_width: 256
  mlp_depth: 4
  kick_in_iter: 0

cnl_mlp:
  xyz_dim: 48
  dir_dim: 16
  mlp_width: 64
  mlp_depth: 2

motionCLIP:
  encoded_feats: 'motionCLIP_token[s]_nbrs[1].pkl' # token: z/s(self); neighborhoods: #neighbors 
  training_frames_poseDistinct: False
  training_frames_lossDistinct: False 


##############################################
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_train'
  batch_size: 1
  shuffle: True
  drop_last: False
  lr: 0.0005  
  lr_mweight_vol_decoder: 0.00005 
  lr_pose_decoder: 0.00005        
  lr_non_rigid_mlp: 0.00005       
  lrate_decay: 100
  optimizer: 'adam'
  ray_shoot_mode: 'patch'
  maxiter: 200000           
  log_interval: 10          
  seed: 0                   
  lossweights:
    lpips: 1.0
    mse: 0.2
    opacity: 1.0             
    l1: 0.2                 
    psnr: 0.0   
  opacity_kick_in_iter: 100000           
  psnr_kick_in_iter: 100000            

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'
  batch_size: 1
  shuffle: False
  drop_last: False
  progress_interval: 1000      
  eval_interval: 10000      

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_387_test'
  batch_size: 1
  shuffle: False
  drop_last: False

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_387_test'
  batch_size: 1
  shuffle: False
  drop_last: False
  frame_idx: 0

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_387_test'
  batch_size: 1
  shuffle: False
  drop_last: False

bgcolor: [0., 0., 0.]

##############################################
## EXPERIMENTS CONFIGURATIONS

resize_img_scale: 0.5       # try: 0.6; [0.5] 

train_keyfilter: ['rays', 'motion_bases', 'motion_weights_priors', 'cnl_bbox', 'dst_posevec_69', 'motionCLIP']
test_keyfilter: ['rays', 'target_rgbs', 'motion_bases', 'motion_weights_priors','cnl_bbox', 'dst_posevec_69', 'motionCLIP']

sex: 'neutral'
total_bones: 24
bbox_offset: 0.3  

resume: True
load_net: latest
save_all: True

patch:
  sample_subject_ratio: 0.8 # [0.8] 
  N_patches: 6             
  size: 20         

network:
  ignore_pose_correction: False
  ignore_non_rigid_motions: False
  apply_hash_coding: True

netchunk_per_gpu: 308000 # dj: [307200=2400*128] number of pts sent through network in parallel, decrease if running out of memory

N_samples: 128      

chunk: 32768   # 32768=1024*32, number of rays processed in parallel, decrease if running out of memory
perturb: 1
n_gpus: 1
num_workers: 1
show_alpha: False  
show_truth: False