category: 'superhumannerf'

##############################################3
## Network Specs

# modules
network_module: 'core.nets.human_nerf.network'
trainer_module: 'core.train.trainers.human_nerf.trainer'
lr_updater_module: 'core.train.trainers.human_nerf.lr_updaters.exp_decay'
optimizer_module: 'core.train.optimizers.human_nerf.optimizer'

# motion weights volume
mweight_volume:
  module: 'core.nets.human_nerf.mweight_vol_decoders.deconv_vol_decoder'
  embedding_size: 256
  volume_size: 32
  dst_voxel_size: 0.0625