category: 'superhumannerf'

##############################################3
## Network Specs

# modules
network_module: 'core.nets.human_nerf.network'
trainer_module: 'core.train.trainers.human_nerf.trainer'
lr_updater_module: 'core.train.trainers.human_nerf.lr_updaters.exp_decay'
optimizer_module: 'core.train.optimizers.human_nerf.optimizer'

# positional embedder -- non-rigid motion mlp
non_rigid_embedder:
  module: "core.nets.human_nerf.embedders.hannw_fourier"

# motion weights volume
mweight_volume:
  module: 'core.nets.human_nerf.mweight_vol_decoders.deconv_vol_decoder'
  embedding_size: 256
  volume_size: 32
  dst_voxel_size: 0.0625

# non-rigid motion mlp
non_rigid_motion_mlp:
  module: 'core.nets.human_nerf.non_rigid_motion_mlps.mlp_offset'
  condition_code_size: 69
  mlp_width: 128
  mlp_depth: 6
  skips: [4]
  multires: 6       # log2 of max freq for positional encoding (3D location)
  i_embed: 0        # set 0 for default positional encoding, -1 for none
  kick_in_iter: 10000
  full_band_iter: 50000

# pose decoder
pose_decoder:
  module: 'core.nets.human_nerf.pose_decoders.mlp_delta_body_pose'
  embedding_size: 69
  mlp_width: 256
  mlp_depth: 4
